# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 96df571bd9d1b74dafa30ecc1b8a74c574a6c9fb043caaff2019a8607a9eeadfc5218171174b85be59aadefa2a4bdfcbf6d35d85418768b35afb69f82bea983e
  github_client_id: d20d8f970019443515f3

test:
  secret_key_base: b5657a6a11f71454795b8bcc8826af72429e6f64afb29cb915c54b213498b011ebeba27f8c2a76f9f5a0def8f95482334b67635344b0fef53e1340bb27cfcc90

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
